name: DragonBliss
version: '1.0'
main: dijon.dragonBliss.DragonBliss
api-version: '1.20'
commands:
  debug:
    usage: /debug
  info:
    usage: /info
  shop:
    usage: /shop
  track:
    usage: /track
  bloodmoon:
    usage: /bloodmoon
  finale:
    usage: /finale
  reseteverything:
    usage: /reseteverything